import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
        <nav className="w-full bg-black shadow px-8 py-4 flex justify-between items-center">
            <div className="flex gap-6 text-lg">
                <a href="/" className="hover:text-blue-600 transition">Home</a>
                <a href="/books" className="hover:text-blue-600 transition">Books</a>
            </div>
        </nav>
    {children}
    </body>
    </html>
  );
}
